# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-12 20:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import filer.fields.file


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('shuup', '0050_move_product_status_text'),
        ('filer', '0010_auto_20180414_2058'),
    ]

    operations = [
        migrations.CreateModel(
            name='FontFamily',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Font family name', max_length=128, verbose_name='name')),
                ('eot', filer.fields.file.FilerFileField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='typography_eot_fonts', to='filer.File', verbose_name='EOT font')),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='typography_fonts', to='shuup.Shop', verbose_name='Shop')),
                ('svg', filer.fields.file.FilerFileField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='typography_svg_fonts', to='filer.File', verbose_name='SVG font')),
                ('ttf', filer.fields.file.FilerFileField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='typography_ttf_fonts', to='filer.File', verbose_name='TTF font')),
                ('woff', filer.fields.file.FilerFileField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='typography_woff_fonts', to='filer.File', verbose_name='WOFF Font')),
                ('woff2', filer.fields.file.FilerFileField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='typography_woff2_fonts', to='filer.File', verbose_name='WOFF2 Font')),
            ],
            options={
                'verbose_name': 'Font Family',
                'verbose_name_plural': 'Font Families',
            },
        ),
        migrations.AlterUniqueTogether(
            name='fontfamily',
            unique_together=set([('shop', 'name')]),
        ),
    ]
